services:
  accounts:
    image: "tle01.accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sparrow11


  loans:
    image: "tle01.loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sparrow11


  cards:
    image: "tle01.cards:s4"
    container_name: cards-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sparrow11

networks:
  sparrow11:
    driver: "bridge"